name: "Terraform: Apply"

on:
  workflow_call:

env:
  TF_APPLY_PARALLELISM_LIMIT: 30

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"

      # Initialize Terraform
      - name: Terraform Init
        run: |
          set -e
          terraform init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve -parallelism=${{ env.TF_APPLY_PARALLELISM_LIMIT }} plan.out

