
name: 'Terraform CI'

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  format:
    uses: ./.github/workflows/base__format.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  plan:
    needs: format
    uses: ./.github/workflows/base__plan.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
